{
  description = "evcxr-lab: Rust research notebooks and REPL sessions powered by evcxr";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      forEachSystem = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      mkLab = pkgs: rec {
        # Jupyter data directory containing only the Rust kernel. Generated by
        # upstream's own `--install` so the logos, kernel.js and version.txt are
        # exactly what this evcxr release expects (a mismatched version.txt makes
        # the kernel try to reinstall itself on startup).
        kernelspec =
          pkgs.runCommand "evcxr-jupyter-kernelspec-${pkgs.evcxr.version}"
            {
              nativeBuildInputs = [
                pkgs.evcxr
                pkgs.jq
              ];
            }
            ''
              export JUPYTER_PATH="$out"
              evcxr_jupyter --install

              # `--install` writes `std::env::current_exe()` into argv, which
              # resolves past nixpkgs' wrapper to `.evcxr_jupyter-wrapped`.
              # Jupyter would then launch the kernel without cargo, rustc and
              # RUST_SRC_PATH on its environment, so point argv back at the
              # wrapper.
              jq --arg exe "${pkgs.evcxr}/bin/evcxr_jupyter" '.argv[0] = $exe' \
                "$out/kernels/rust/kernel.json" >kernel.json
              mv kernel.json "$out/kernels/rust/kernel.json"
            '';

        # Jupyter itself. `nbconvert`/`nbclient` are what make notebooks
        # executable from the command line (useful for re-running an experiment
        # or checking one in CI).
        jupyter = pkgs.python3.withPackages (ps: [
          ps.jupyterlab
          ps.notebook
          ps.nbconvert
          ps.nbclient
        ]);

        # `jupyter lab` with the Rust kernel already registered, for use without
        # entering the dev shell: `nix run .#lab`.
        lab = pkgs.writeShellApplication {
          name = "evcxr-lab";
          runtimeInputs = [ jupyter ];
          text = ''
            export JUPYTER_PATH="${kernelspec}''${JUPYTER_PATH:+:$JUPYTER_PATH}"
            exec jupyter lab "$@"
          '';
        };

        shell = pkgs.mkShell {
          name = "evcxr-lab";

          packages = [
            pkgs.evcxr # `evcxr` REPL + `evcxr_jupyter` kernel
            jupyter
            pkgs.cargo
            pkgs.rustc
            pkgs.clippy
            pkgs.rustfmt
            pkgs.rust-analyzer
            pkgs.pkg-config # so `:dep` crates with -sys deps can find libraries
          ];

          # Used by rust-analyzer and by evcxr's completions.
          env.RUST_SRC_PATH = "${pkgs.rustPlatform.rustLibSrc}";

          shellHook = ''
            # Register the Rust kernel without writing into $HOME. Note that
            # `evcxr_jupyter --install` is *not* needed (and would fail, since
            # this path is in the read-only Nix store).
            export JUPYTER_PATH="${kernelspec}''${JUPYTER_PATH:+:$JUPYTER_PATH}"

            # Keep Jupyter's config/state/sockets inside the repo instead of
            # $HOME, so labs are self-contained and disposable.
            lab_root="$(${pkgs.git}/bin/git rev-parse --show-toplevel 2>/dev/null || pwd)"
            export JUPYTER_CONFIG_DIR="$lab_root/.jupyter/config"
            export JUPYTER_DATA_DIR="$lab_root/.jupyter/data"
            export JUPYTER_RUNTIME_DIR="$lab_root/.jupyter/runtime"
            mkdir -p "$JUPYTER_CONFIG_DIR" "$JUPYTER_DATA_DIR" "$JUPYTER_RUNTIME_DIR"

            echo "evcxr-lab: $(evcxr --version), $(rustc --version)"
            echo "  jupyter lab      start the notebook server (Rust kernel)"
            echo "  evcxr            start the Rust REPL"
          '';
        };
      };

      perSystem = forEachSystem mkLab;
    in
    {
      packages = nixpkgs.lib.mapAttrs (_: lab: {
        default = lab.lab;
        inherit (lab) kernelspec jupyter lab;
      }) perSystem;

      apps = nixpkgs.lib.mapAttrs (
        system: lab:
        let
          app = {
            type = "app";
            program = nixpkgs.lib.getExe lab.lab;
          };
        in
        {
          default = app;
          lab = app;
        }
      ) perSystem;

      devShells = nixpkgs.lib.mapAttrs (_: lab: { default = lab.shell; }) perSystem;

      checks = nixpkgs.lib.mapAttrs (
        system: lab:
        let
          pkgs = nixpkgs.legacyPackages.${system};
        in
        {
          # Guards the argv rewrite above: a kernelspec pointing at a
          # non-executable path, or at the unwrapped binary, is silently broken
          # until someone opens a notebook.
          kernelspec = pkgs.runCommand "check-evcxr-kernelspec" { nativeBuildInputs = [ pkgs.jq ]; } ''
            spec="${lab.kernelspec}/kernels/rust/kernel.json"
            exe="$(jq -r '.argv[0]' "$spec")"
            echo "kernel argv[0]: $exe"
            test -x "$exe" || { echo "argv[0] is not executable" >&2; exit 1; }
            case "$exe" in
              *.evcxr_jupyter-wrapped)
                echo "argv[0] bypasses the nixpkgs wrapper" >&2; exit 1 ;;
            esac
            [ "$(jq -r '.language' "$spec")" = rust ]
            test -e "${lab.kernelspec}/kernels/rust/version.txt"
            touch "$out"
          '';
        }
      ) perSystem;

      formatter = forEachSystem (pkgs: pkgs.nixfmt-tree);
    };
}
